SII/backend/controllers/FilesController.php
<?php

namespace backend\controllers;

use common\models\BusinessEnvironment;
use common\models\Scenario;
use common\models\Video;
use Yii;
use yii\helpers\FileHelper;
use yii\web\UploadedFile;
use app\models\UploadImageForm;
use app\models\UploadDocumentForm;
use app\models\UploadVideoForm;
use yii\filters\AccessControl;
use common\models\Documents;

class FilesController extends \yii\web\Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actionImage()
    {
        return $this->render('images');
    }

    public function actionImagesLoad()
    {
        $model = new UploadImageForm();

        if (Yii::$app->request->isPost) {
            $model->imageFiles = UploadedFile::getInstances($model, 'imageFiles');
            if ($model->upload()) {
                return $this->redirect(['image']);
            }
        }

        return $this->render('image', ['model' => $model]);
    }

    public function actionImageDelete()
    {
        $request = Yii::$app->request;
        $file = $request->get('file');
        unlink($file);
        Yii::$app->session->setFlash('success', 'Файл успешно удален.');
        return $this->actionImage();
    }

    public function actionVideo()
    {
        $videos = Video::find()->all();
        return $this->render('videos', ['videos' => $videos]);
    }

    public function actionVideoLoad()
    {
        $request = Yii::$app->request;
        if ($request->isGet)
        {
            return $this->render('video');
        }
        if ($request->isPost)
        {
            $video = new Video();
            if (Video::find()->count() == 0)
            {
                $video->id = 1;
            }
            else
            {
                $video->id = Video::find()->all()[Video::find()->count() - 1]->id + 1;
            }
            $video->name = $request->post('name');
            $video->code = $request->post('code');
            if ($video->save())
            {
                Yii::$app->session->setFlash('success', 'Видео успешно добавлено.');
                $this->redirect(['video']);
            }
        }
    }

    public function actionVideoUpdate()
    {
        $request = Yii::$app->request;
        $video = Video::find()->where(['id' => (int)$request->get('id')])->one();
        if ($request->isGet)
        {
            return $this->render('videoUpdateForm', ['video' => $video]);
        }
        if ($request->isPost)
        {
            $video->name = $request->post('name');
            $video->code = $request->post('code');
            if ($video->save())
            {
                Yii::$app->session->setFlash('success', 'Сведения о видео успешно изменены.');
                $this->redirect(['video']);
            }
        }
    }

    public function actionVideoDelete()
    {
        $request = Yii::$app->request;
        $video = Video::find()->where(['id' => (int)$request->get('id')])->one();
        if ($request->isGet)
        {
            return $this->render('videoDelete', ['video' => $video]);
        }
        if ($request->isPost)
        {
            if ($video->delete())
            {
                /*$categories = BusinessEnvironment::find()->all();
                foreach ($categories as $category)
                {
                    $scenario = Scenario::find()->where(['categoryID' => $category->id])->one();
                    if ((int)$scenario['settings']['videoID'] == (int)$request->get('id'))
                    {
                        $scenario['settings']['videoID'] = null;
                        $scenario['settings']['hasVideo'] = false;
                        $scenario->save();
                    }
                }*/
                Yii::$app->session->setFlash('success', 'Видео успешно удалено.');
                $this->redirect(['video']);
            }
        }
    }

    public function actionDocument()
    {
        return $this->render('documents');
    }

    public function actionUpdateDocument()
    {
        $request = Yii::$app->request;
        if(Yii::$app->request->isGet)
        {
            $id = (int)$request->get('id');
            $document = Documents::find()->where(['id' => $id])->one();
            return $this->render('updateDocumentForm', ['document' => $document]);
        }
        if(Yii::$app->request->isPost)
        {
            $id = (int)$request->get('id');
            $document = Documents::find()->where(['id' => $id])->one();
            $document->short_name = $request->post('ShortName');
            $document->full_name = $request->post('FullName');
            $document->save();
            Yii::$app->session->setFlash('success', 'Изменения успешно сохранены.');
            return $this->actionDocument();
        }
    }

    public function actionDocumentUpload()
    {
        $model = new UploadDocumentForm();

        if (Yii::$app->request->isPost) {
            $model->file = UploadedFile::getInstance($model, 'file');
            if ($model->file && $model->validate()) {
                $model->file->saveAs('../documents/' . FilesController::transliteration($model->file->baseName) . '.' . $model->file->extension);
                $document = new Documents();
                if (Documents::find()->count() == 0)
                {
                    $document->id = 1;
                }
                else
                {
                    $document->id = Documents::find()->all()[Documents::find()->count() - 1]->id + 1;
                }

                $document->url = './documents/' . FilesController::transliteration($model->file->baseName) . '.' . $model->file->extension;
                $document->full_name = Yii::$app->request->post('UploadDocumentForm')['fullDocName'];
                $document->short_name = Yii::$app->request->post('UploadDocumentForm')['shortDocName'];
                $document->extension = $model->file->extension;
                $document->save();
                Yii::$app->session->setFlash('success', 'Документ успешно загружен.');
            }
        }
        return $this->render('document', ['model' => $model]);
    }

    public function actionDeleteDocument()
    {
        $request = Yii::$app->request;
        if(Yii::$app->request->isGet)
        {
            $id = (int)$request->get('id');
            $document = Documents::find()->where(['id' => $id])->one();
            return $this->render('documentDelete', ['document' => $document]);
        }
        if(Yii::$app->request->isPost)
        {
            $id = (int)$request->get('id');
            $document = Documents::find()->where(['id' => $id])->one();
            $path = '.' . $document->url;
            $document->delete();
            unlink($path);
            Yii::$app->session->setFlash('success', 'Документ успешно удален.');
            return $this->actionDocument();
        }
    }

    public static function transliteration($text){

        $trans_arr = array (
            "а"=>"a","б"=>"b","в"=>"v","г"=>"g","д"=>"d",
            "е"=>"e", "ё"=>"yo","ж"=>"j","з"=>"z","и"=>"i",
            "й"=>"i","к"=>"k","л"=>"l", "м"=>"m","н"=>"n",
            "о"=>"o","п"=>"p","р"=>"r","с"=>"s","т"=>"t",
            "у"=>"y","ф"=>"f","х"=>"h","ц"=>"c","ч"=>"ch",
            "ш"=>"sh","щ"=>"sh","ы"=>"i","э"=>"e","ю"=>"u",
            "я"=>"ya",
            "А"=>"A","Б"=>"B","В"=>"V","Г"=>"G","Д"=>"D",
            "Е"=>"E","Ё"=>"Yo","Ж"=>"J","З"=>"Z","И"=>"I",
            "Й"=>"I","К"=>"K","Л"=>"L","М"=>"M","Н"=>"N",
            "О"=>"O","П"=>"P","Р"=>"R","С"=>"S","Т"=>"T",
            "У"=>"Y","Ф"=>"F","Х"=>"H","Ц"=>"C","Ч"=>"Ch",
            "Ш"=>"Sh","Щ"=>"Sh","Ы"=>"I","Э"=>"E","Ю"=>"U",
            "Я"=>"Ya",
            "ь"=>"","Ь"=>"","ъ"=>"","Ъ"=>"",
            "ї"=>"j","і"=>"i","ґ"=>"g","є"=>"ye",
            "Ї"=>"J","І"=>"I","Ґ"=>"G","Є"=>"YE",
            " " => ""
        );

        return strtr($text, $trans_arr);

    }
}

SII/backend/controllers/ScenarioController.php
<?php

namespace backend\controllers;

use common\models\Video;
use Yii;
use yii\web\Controller;
use common\models\BusinessEnvironment;
use common\models\Scenario;
use yii\filters\AccessControl;
use yii\helpers\Json;
use yii\helpers\ArrayHelper;
use yii\web\Response;

class ScenarioController extends Controller
{
    public $layout = 'scenarioEditor';

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {
        if ($action->id === 'save' || $action->id === 'load') {
            $this->enableCsrfValidation = false;
        }
        return parent::beforeAction($action);
    }

    /*
     * Вывод списка сценариев
     */
    public function actionIndex()
    {
        $this->layout = 'main';
        $scenarios = Scenario::find()->all();
        $categories = [];
        foreach($scenarios as $scenario)
        {
            $categories[] = [
                'id' => $scenario->categoryID,
                'name' => BusinessEnvironment::getCategoryName($scenario->categoryID)
            ];
        }
        ArrayHelper::multisort($categories, 'id', [SORT_ASC]);
        return $this->render('index', ['categories' => $categories]);
    }

    /*
     * Вывод редактора сценариев и контента
     */
    public function actionEditor()
    {
        $request = Yii::$app->request;
        $id = (int)$request->get('id');
        $session = Yii::$app->session;
        $session->set('categoryID', $id);
        return $this->render('scenario', [
            'id' => $id,
        ]);
    }

    /**
     * Выгразка сценария в редактор
     */
    public function actionLoad()
    {
        $session = Yii::$app->session;
        $id = $session->get('categoryID');
        $scenario = Scenario::find()->where(['categoryID' => $id])->one();
        $categoryName = BusinessEnvironment::getCategoryName($id);
        $response = Yii::$app->response;
        $response->format = Response::FORMAT_JSON;
        $response->data = ['categoryName' => $categoryName, 'scenario' => $scenario];
        $response->send();
    }

    /*
     * Сохранение сценария
     */
    public function actionSave()
    {
        $request = Yii::$app->request;
        $session = Yii::$app->session;
        $categoryID = $session->get('categoryID');
        $scenario = Scenario::find()->where(['categoryID' => $categoryID])->one();
        $manualScenario = $request->post('scenario');
        $settings = $request->post('settings');
        $manualScenario = Json::decode($manualScenario);
        $settings = Json::decode($settings);
        $scenario->manual_scenario = $manualScenario;
        $scenario->settings = $settings;
        if ($scenario->save())
        {
            Yii::$app->response->statusCode = 200;
        }
        else
        {
            Yii::$app->response->statusCode = 500;
        }

    }
}

SII/backend/controllers/SettingsController.php
<?php

namespace backend\controllers;

use yii\web\Controller;
use yii\filters\AccessControl;
use Yii;
use common\models\Settings;

class SettingsController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actionBase()
    {
        $request = Yii::$app->request;
        /*
         * Вывод формы базовых настроек
         */
        if(Yii::$app->request->isGet)
        {
            $siteName = Settings::getSiteName();
            $siteStatus = Settings::getSiteStatus();
            $settings = [
                'siteName' => $siteName,
                'siteStatus' => $siteStatus
            ];
            return $this->render('base', ['settings' => $settings]);
        }
        /*
         *Сохранение базовых настроек
         */
        if(Yii::$app->request->isPost)
        {
            $siteName = $request->post('siteName');
            Settings::setSiteName($siteName);

            $siteStatus = $request->post('siteStatus');
            Settings::setSiteStatus($siteStatus);

            Yii::$app->session->setFlash('success', 'Изменения успешно сохранены.');
            return $this->redirect(['base']);
        }

    }

    /**
     * Установка логотипа сайта
     */
    public function actionLogo()
    {
        $request = Yii::$app->request;
        $file = $request->get('file');
        $path = strtr($file, ['..' => '.']);
        Settings::setLogo($path);
        Yii::$app->session->setFlash('success', 'Изображение установлено как логотип.');
        return $this->redirect(['files/image']);
    }

}

SII/backend/views/layouts/collectionsEditor.php
<?php
use backend\assets\CollectionsAsset;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this \yii\web\View */
/* @var $content string */

CollectionsAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>" ng-app="DataCollectionsApp">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<?php $this->beginBody() ?>
<body class="hold-transition skin-blue" ng-controller="MainController">
<div class="wrapper">

    <header class="main-header">
        <a class="logo" style="width: 60px;">
            <i class="fa fa-hdd-o fa-2x" style="margin-left: -4px; margin-top: 5px;"></i>
        </a>
        <a class="navbar-brand">Коллекции данных</a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top" role="navigation">
            <div class="navbar-header">
                <div>
                    <a href="<?= Url::home() ?>" class="btn btn-default navbar-btn"><i class="fa fa-reply"></i> Назад в главное меню</a>
                </div>
            </div>
        </nav>
    </header>

    <!-- =============================================== -->

    <!-- Left side column. contains the sidebar -->
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar" style="margin-top: 50px;">
            <ul class="sidebar-menu">
                <li ng-repeat="collection in collections" class="{{collection == currentCollection? 'active' : ''}}">
                    <a ng-click="editingCollection(collection)" class="sidebar-button">
                        <i class="fa fa-database fa-2x">  </i>
                        <span style="font-size: 20px; margin-left: 5px; white-space: normal;"> {{collection.collection_name}}</span>
                    </a>
                </li>
            </ul>
        </section>
        <button class="btn btn-success" style="width: 95%; margin-left: 5px; margin-right: 5px;" ng-click="creatingCollection()"><i class="fa fa-plus"></i> Создать коллекцию   </button>
        <!-- /.sidebar -->
    </aside>

    <!-- =============================================== -->

    <!-- Рабочая область -->
    <div class="content-wrapper" style="padding-bottom: 10px; height: auto;">
        <?= $content ?>
    </div>

</div>
</body>
<?php $this->endBody() ?>
</html>
<?php $this->endPage() ?>

SII/backend/views/layouts/empty.php
<?php
use backend\assets\AppAsset;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;

/* @var $this \yii\web\View */
/* @var $content string */

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>
<div class="wrap" style="display: flex;">
    <div class="container" style="display: flex; margin: auto">
        <div class="col-md-4 well" style="margin: auto">
            <?= $content ?>
        </div>
    </div>
</div>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

SII/backend/views/layouts/main-old.php
<?php
use backend\assets\AppAsset;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use frontend\widgets\Alert;

/* @var $this \yii\web\View */
/* @var $content string */

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
    <?php $this->beginBody() ?>
    <div class="wrap">
        <div class="container-fluid">
            <div class="row-fluid">
                <div class="col-md-2 sidebar list-group" >
                    <?php

                    $menuItems = [
                        ['label' => 'Главная', 'url' => ['/site/index']],
                        "<hr>",
                        "<h5>Настройки </h5>",
                        [
                            'label' => 'Базовые настройки',
                            'url' => ['/settings/base']
                        ],
                        [
                            'label' => 'Работа с файлами',
                            'items' => [
                                [
                                    'label' => 'Изображения',
                                    'url' => ['/files/image'],
                                ],
                                [
                                    'label' => 'Видео',
                                    'url' => ['/files/video']
                                ],
                                [
                                    'label' => 'Документы',
                                    'url' => ['/files/document']
                                ],
                            ],
                        ],
                        [
                            'label' => 'Деловое окружение',
                            'url' => ['/environment/index']
                        ],

                        "<hr>",

                        "<h5>Управление контентом </h5>",
                        [
                            'dropDownOptions' => ['class' => 'dropdown-menu-right'],
                            'label' => 'Стандартные страницы',
                            'items' => [
                                [
                                    'label' => 'Приветствие',
                                    'url' => ['/pages/hello'],
                                    'dropDownOptions' => ['class' => 'dropdown-submenu'],
                                ],
                                [
                                    'label' => 'Контакты',
                                    'url' => ['/pages/contacts']
                                ],
                                [
                                    'label' => 'Помощь',
                                    'url' => ['/pages/help']
                                ],
                                [
                                    'label' => 'Документы',
                                    'url' => ['/pages/documents']
                                ],
                                [
                                    'label' => 'Партнерство',
                                    'url' => ['/pages/partnership']
                                ],
                            ],

                        ],
                        [
                            'label' => 'Сценарии',
                            'url' => ['/scenario/index']
                        ],

                        "<hr>",

                        "<h5>Управление пользователями </h5>",

                        "<hr>",

                        "<h5>Мониторинг информационного воздействия </h5>",
                        [
                            'label' => 'Обратная связь',
                            'url' => ['/monitoring/feedbacks']
                        ],
                        [
                            'label' => 'Мониторинг поведения',
                            'url' => './analytics'
                        ],

                        "<hr>"

                    ];
                    if (Yii::$app->user->isGuest) {
                        $menuItems[] = ['label' => 'Login', 'url' => ['/site/login']];
                    } else {
                        $menuItems[] = [
                            'label' => 'Выход (' . Yii::$app->user->identity->username . ')',
                            'url' => ['/site/logout'],
                            'linkOptions' => ['data-method' => 'post']
                        ];
                    }
                    echo Nav::widget([
                        'options' => ['class' => 'nav-pills nav-stacked list-group-item'], //nav-list bs-docs-sidenav nav-collapse nav-pills nav-stacked list-group-item
                        'items' => $menuItems,

                    ]);

                    ?>
                </div>
                <div class="col-md-10 main">
                    <?= Alert::widget() ?>
                    <?= $content ?>
                </div>
            </div>
        </div>
    </div>
    <?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

SII/backend/views/layouts/main.php
<?php
use yii\BaseYii;
use backend\assets\AppAsset;
use yii\helpers\Html;
use common\models\Feedback;
use frontend\widgets\Alert;
use yii\helpers\Url;

/* @var $this \yii\web\View */
/* @var $content string */

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>

<body class="hold-transition skin-blue sidebar-mini">

<div class="wrapper">
    <!-- Left side column. contains the sidebar -->
    <aside class="main-sidebar">

        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar" style="padding: 0">
            <!-- sidebar menu: : style can be found in sidebar.less -->
            <ul class="sidebar-menu">
                <li class="header">ПОДГОТОВКА</li>
                <li <?php if (Yii::$app->request->getUrl() == Url::to(['settings/base'])) echo 'class="active"' ?>>
                    <a href="<?= Url::to(['settings/base']) ?>">Базовые настройки</a>
                </li>
                <li>
                    <a href="#"> Работа с файлами</a>
                    <ul class="treeview-menu">
                        <li <?php if (Yii::$app->request->getUrl() == Url::to(['files/image'])) echo 'class="active"' ?>><a href="<?= Url::to(['files/image']) ?>"> Изображения</a></li>
                        <li <?php if (Yii::$app->request->getUrl() == Url::to(['files/video'])) echo 'class="active"' ?>><a href="<?= Url::to(['files/video']) ?>"> Видео</a></li>
                        <li <?php if (Yii::$app->request->getUrl() == Url::to(['files/document'])) echo 'class="active"' ?>><a href="<?= Url::to(['files/document']) ?>"> Документы</a></li>
                    </ul>
                </li>

                <li <?php if (Yii::$app->request->getUrl() == Url::to(['environment/index'])) echo 'class="active"' ?>>
                    <a href="<?= Url::to(['environment/index']) ?>">Деловое окружение</a>
                </li>
                <li class="header">УПРАВЛЕНИЕ КОНТЕНТОМ</li>
                <li class="treeview">
                    <a href="#">
                        <span>Стандартные страницы</span>
                    </a>
                    <ul class="treeview-menu">
                        <li <?php if (Yii::$app->request->getUrl() == Url::to(['pages/hello'])) echo 'class="active"' ?>>
                            <a href="<?= Url::to(['pages/hello']) ?>">Приветствие</a>
                        </li>
                        <li <?php if (Yii::$app->request->getUrl() == Url::to(['pages/contacts'])) echo 'class="active"' ?>>
                            <a href="<?= Url::to(['pages/contacts']) ?>">Контакты</a>
                        </li>
                        <li <?php if (Yii::$app->request->getUrl() == Url::to(['pages/help'])) echo 'class="active"' ?>>
                            <a href="<?= Url::to(['pages/help']) ?>">Помощь</a>
                        </li>
                        <li <?php if (Yii::$app->request->getUrl() == Url::to(['pages/partnership'])) echo 'class="active"' ?>>
                            <a href="<?= Url::to(['pages/partnership']) ?>">Партнерство</a>
                        </li>
                    </ul>
                </li>
                <li <?php if (Yii::$app->request->getUrl() == Url::to(['scenario/index'])) echo 'class="active"' ?>>
                    <a href="<?= Url::to(['scenario/index']) ?>"><span>Сценарии</span></a>
                </li>
                <li <?php if (Yii::$app->request->getUrl() == Url::to(['collections/workspace'])) echo 'class="active"' ?>>
                    <a href="<?= Url::to(['collections/workspace']) ?>"><span>Коллекции данных</span></a>
                </li>

                <li class="header">МОНИТОРИНГ</li>
                <li <?php if (Yii::$app->request->getUrl() == Url::to(['monitoring/feedbacks'])) echo 'class="active"' ?>>
                    <a href="<?= Url::to(['monitoring/feedbacks']) ?>">
                        <span>Обратная связь</span>
                        <?php
                        $countUnreadMessages = Feedback::getCountOfUnreadMessages();
                        if ($countUnreadMessages > 0): ?>
                        <small class="label pull-right bg-green"><?= $countUnreadMessages ?></small>
                        <?php endif; ?>
                    </a>
                </li>
                <li><a target="_blank" href="<?= Url::to('./analytics') ?>"><span>Аналитика</span></a></li>

                <li class="header">УПРАВЛЕНИЕ ПОЛЬЗОВАТЕЛЯМИ</li>
                <li>
                    <a>Роли</a>
                </li>
                <li>
                    <a>Пользователи</a>
                </li>

                <li class="header"><?= Yii::$app->user->identity->username ?></li>

                <li <?php if (Yii::$app->request->getUrl() == Url::to(['site/index'])) echo 'class="active"' ?>>
                    <a href="<?= Url::to(['site/index']) ?>"><span>Главное меню</span></a>
                </li>

                <li>
                    <a href="../" target="_blank"><span>Web-ресурс</span></a>
                </li>

                <li> <a data-method="post" href="<?= Url::to(['site/logout']) ?>"><span>Выход</span></a></li>


        </section>
        <!-- /.sidebar -->
    </aside>

    <!-- =============================================== -->

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper" style="height: 100%;">
        <div class="alert-container"><?= Alert::widget() ?></div>
        <?= $content ?>
    </div><!-- /.content-wrapper -->
</div><!-- ./wrapper -->
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>