SII/frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use common\models\BusinessEnvironment;
use common\models\Documents;
use common\models\Settings;
use common\models\Feedback;
use Yii;
use frontend\models\ContactForm;
use yii\web\Controller;

/**
 * Site controller
 */
class SiteController extends Controller
{

    public function beforeAction($action)
    {
        if ($action->id != 'not-available')
        {
            if (Settings::getSiteStatus() == 'NotAvailable')
            {
                $this->redirect(['not-available']);
            }
        }
        return parent::beforeAction($action);
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        $this->layout = 'title';
        $hello = Settings::getHelloPage();
        $hello = strtr($hello, ['src="..' => 'src=".', 'alt="..' => 'alt=".', '<img' => '<img class="img-responsive"']);
        $mainCategories = BusinessEnvironment::getMainCategories();
        $advancedCategories = BusinessEnvironment::getAdvancedCategories();
        return $this->render('index',
            [
                'hello' => $hello,
                'mainCategories' => $mainCategories,
                'advancedCategories' => $advancedCategories
            ]);
    }

    public function actionNotAvailable()
    {
        $this->layout = 'empty';
        return $this->render('notAvailable');
    }

    public function actionFeedback()
    {
        $this->layout = 'standart';
        $model = new ContactForm();
        if (Yii::$app->request->isPost)
        {
            if ($model->load(Yii::$app->request->post()) && $model->validate()) {
                $feedbackRecord = new Feedback();
                $feedbackRecord->id = Feedback::find()->count();
                $feedbackRecord->name = $model->name;
                $feedbackRecord->category = $model->category;
                $feedbackRecord->email = $model->email;
                $feedbackRecord->subject = $model->subject;
                $feedbackRecord->body = $model->body;
                $feedbackRecord->date = date('c');
                $feedbackRecord->is_readed = false;
                if ($feedbackRecord->save()) {
                    Yii::$app->session->setFlash('success', 'Спасибо за то, что вы связались с нами. Мы ответим вам сразу как это будет возможно.');
                } else {
                    Yii::$app->session->setFlash('error', 'Произошла ошибка.');
                }
                return $this->refresh();
            }
        }
        else {
            return $this->render('feedback', [
                'model' => $model,
            ]);
        }
    }

    public function actionHelp()
    {
        $this->layout = 'standart';
        return $this->render('help');
    }

    /*public function actionDocuments()
    {
        $this->layout = 'standart';
        $documents = Documents::find()->all();
        return $this->render('documents', ['documents' => $documents]);
    }*/

    public function actionPartnership()
    {
        $this->layout = 'standart';
        return $this->render('partnership');
    }

    public function actionContacts()
    {
        $this->layout = 'standart';
        $page = Settings::getContactsPage();
        return $this->render('contacts', ['page' => $page]);
    }
}

SII/frontend/views/layouts/empty.php
<?php
use backend\assets\AppAsset;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;

/* @var $this \yii\web\View */
/* @var $content string */

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>
<div class="wrap" style="display: flex;">
    <div class="container" style="display: flex; margin: auto">
        <div class="col-md-4 well" style="margin: auto">
            <?= $content ?>
        </div>
    </div>
</div>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

SII/frontend/views/layouts/main.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use common\models\Settings;
use frontend\assets\AppAsset;
use frontend\widgets\Alert;

/* @var $this \yii\web\View */
/* @var $content string */

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
    <?php $this->beginBody() ?>
    <div class="wrap">
        <?php
        NavBar::begin([
            'brandLabel' => "<img src='".Url::to([Settings::getLogo()])."' style='height: 40px; margin-top: 5px; margin-bottom: 5px;'>",
            'brandUrl' => Yii::$app->homeUrl,
            'options' => [
                'class' => 'navbar-default navbar-static-top',
            ],
        ]);
        $menuItems = [
            ['label' =>  'Контакты', 'url' => ['/site/contacts']],
            ['label' => 'Помощь', 'url' => ['/site/help']],
        ];
        echo Nav::widget([
            'options' => ['class' => 'navbar-nav navbar-right', 'style' => 'font-weight: bold; font-size: 18px;'],
            'items' => $menuItems,
        ]);
        echo Nav::widget([
            'options' => ['class' => 'navbar-nav navbar-right', 'style' => 'font-weight: bold; font-size: 18px;'],
            'encodeLabels' => false,
            'items' =>  [
                [
                    'label' => Breadcrumbs::widget([
                        'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                        'homeLink' => false
                    ]),
                    'options' => ['class' => 'hidden-xs'],
                    'linkOptions' => [
                        'style' => 'font-weight: bold; font-size: 16px; display: none;'
                    ],
                ],
                [
                    'label' =>  '|',
                    'options' => ['class' => 'hidden-xs'],
                    'linkOptions' => ['style' => 'font-size: 24px; font-weight: lighter;'],

                ],
            ],
        ]);
        NavBar::end();
        ?>
        <?= Alert::widget() ?>
        <?= $content ?>

    </div>

    <footer class="footer">
        <?php
        NavBar::begin([
            'options' => [
                'class' => 'navbar-default',
            ],
        ]);
        $menuItems = [
            ['label' =>  'Партнерство', 'url' => ['/site/partnership']],
        ];
        echo Nav::widget([
            'options' => ['class' => 'navbar-nav navbar-left', 'style' => 'font-weight: bold; font-size: 18px;'],
            'items' => $menuItems,
        ]);
        $menuItems = [
            ['label' =>  'Связаться с нами', 'url' => ['/site/feedback']],
        ];
        echo Nav::widget([
            'options' => ['class' => 'navbar-nav navbar-right', 'style' => 'font-weight: bold; font-size: 18px;'],
            'items' => $menuItems,
        ]);
        NavBar::end();
        ?>
    </footer>
    <!-- Piwik -->
    <script type="text/javascript">
        var _paq = _paq || [];
        _paq.push(['trackPageView']);
        _paq.push(['enableLinkTracking']);
        (function() {
            var u="<?= Url::base() ?>/control/analytics/";
            _paq.push(['setTrackerUrl', u+'piwik.php']);
            _paq.push(['setSiteId', 1]);
            var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
            g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
        })();
    </script>
    <noscript>
        <p>
            <img src="<?= Url::base() ?>/control/analytics/piwik.php?idsite=1" style="border:0;" alt="" />
        </p>
    </noscript>
    <!-- End Piwik Code -->
    <?php $this->endBody() ?>

</body>
</html>
<?php $this->endPage() ?>

SII/frontend/views/layouts/standart.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use common\models\Settings;
use frontend\assets\AppAsset;
use frontend\widgets\Alert;

/* @var $this \yii\web\View */
/* @var $content string */

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>
<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => "<img src='".Url::to([Settings::getLogo()])."' style='height: 40px; margin-top: 5px; margin-bottom: 5px;'>",
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-default navbar-static-top',
        ],
    ]);
    $menuItems = [
        ['label' =>  'Контакты', 'url' => ['/site/contacts']],
        ['label' => 'Помощь', 'url' => ['/site/help']],
    ];
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right', 'style' => 'font-weight: bold; font-size: 18px;'],
        'items' => $menuItems,
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right', 'style' => 'font-weight: bold; font-size: 18px;'],
        'encodeLabels' => false,
        'items' =>  [
            [
                'label' => Breadcrumbs::widget([
                    'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                    'homeLink' => false
                ]),
                'options' => ['class' => 'hidden-xs'],
                'linkOptions' => [
                    'style' => 'font-weight: bold; font-size: 16px; display: none;'
                ],
            ],
            [
                'label' =>  '|',
                'options' => ['class' => 'hidden-xs'],
                'linkOptions' => ['style' => 'font-size: 24px; font-weight: lighter;'],

            ],
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">

        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <?php
    NavBar::begin([
        'options' => [
            'class' => 'navbar-default',
        ],
    ]);
    $menuItems = [
        ['label' =>  'Партнерство', 'url' => ['/site/partnership']],
    ];
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-left', 'style' => 'font-weight: bold; font-size: 18px;'],
        'items' => $menuItems,
    ]);
    $menuItems = [
        ['label' =>  'Связаться с нами', 'url' => ['/site/feedback']],
    ];
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right', 'style' => 'font-weight: bold; font-size: 18px;'],
        'items' => $menuItems,
    ]);
    NavBar::end();
    ?>
</footer>
<!-- Piwik -->
<script type="text/javascript">
    var _paq = _paq || [];
    _paq.push(['trackPageView']);
    _paq.push(['enableLinkTracking']);
    (function() {
        var u="<?= Url::base() ?>/control/analytics/";
        _paq.push(['setTrackerUrl', u+'piwik.php']);
        _paq.push(['setSiteId', 1]);
        var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
        g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
    })();
</script>
<noscript>
    <p>
        <img src="<?= Url::base() ?>/control/analytics/piwik.php?idsite=1" style="border:0;" alt="" />
    </p>
</noscript>
<!-- End Piwik Code -->
<?php $this->endBody() ?>

</body>
</html>
<?php $this->endPage() ?>

SII/frontend/views/layouts/title.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use frontend\assets\AppAsset;
use frontend\widgets\Alert;
use common\models\Settings;


/* @var $this \yii\web\View */
/* @var $content string */

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
    <?php $this->beginBody() ?>
    <div class="wrap">
        <?php
        NavBar::begin([

        ]);
        $menuItems = [
            ['label' =>  'Контакты', 'url' => ['/site/contacts']],
            ['label' => 'Помощь', 'url' => ['/site/help']],
        ];

        echo Nav::widget([
            'options' => ['class' => 'navbar-nav navbar-right', 'style' => 'font-weight: bold; font-size: 18px;'],
            'items' => $menuItems,
        ]);


        NavBar::end();
        ?>

        <div class="container">

            <?= Alert::widget() ?>
            <?= $content ?>
        </div>
    </div>

    <footer class="footer">
        <?php
        NavBar::begin([
            'options' => [
                'class' => 'navbar-default',
            ],
        ]);
        $menuItems = [
            ['label' =>  'Партнерство', 'url' => ['/site/partnership']],
        ];
        echo Nav::widget([
            'options' => ['class' => 'navbar-nav navbar-left', 'style' => 'font-weight: bold; font-size: 18px;'],
            'items' => $menuItems,
        ]);
        $menuItems = [
            ['label' =>  'Связаться с нами', 'url' => ['/site/feedback']],
        ];
        echo Nav::widget([
            'options' => ['class' => 'navbar-nav navbar-right', 'style' => 'font-weight: bold; font-size: 18px;'],
            'items' => $menuItems,
        ]);
        NavBar::end();
        ?>
    </footer>
    <div>
        <?php $this->endBody() ?>
        <!-- Piwik -->
        <script type="text/javascript">
            var _paq = _paq || [];
            _paq.push(['trackPageView']);
            _paq.push(['enableLinkTracking']);
            (function() {
                var u="<?= Url::base() ?>/control/analytics/";
                _paq.push(['setTrackerUrl', u+'piwik.php']);
                _paq.push(['setSiteId', 1]);
                var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
                g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
            })();
        </script>
        <noscript>
            <p>
                <img src="<?= Url::base() ?>/control/analytics/piwik.php?idsite=1" style="border:0;" alt="" />
            </p>
        </noscript>
    </div>
</body>
</html>
<?php $this->endPage() ?>