SII/backend/controllers/EnvironmentController.php
<?php

namespace backend\controllers;
use common\models\BusinessEnvironment;
use common\models\Scenario;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;


class EnvironmentController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionCreate()
    {
        $request = Yii::$app->request;
        if(Yii::$app->request->isGet)
        {
            return $this->render('createForm');
        }
        if(Yii::$app->request->isPost)
        {
            $categoryName = $request->post('CategoryName');
            $categoryStatus = (int)$request->post('Main');

            //Проверка уникальности имени
            $exclusiveName = true;
            $categories = BusinessEnvironment::find()->all();
            foreach ($categories as $category)
            {
                if ($category->name == $categoryName)
                {
                    $exclusiveName = false;
                    break;
                }
            }
            if ($exclusiveName)
            {
                $category = new BusinessEnvironment();
                if (BusinessEnvironment::find()->count() == 0)
                {
                    $category->id = 1;
                }
                else
                {
                    $category->id = BusinessEnvironment::find()->all()[BusinessEnvironment::find()->count() - 1]->id + 1;
                }
                $category->name = $categoryName;
                $category->main = $categoryStatus;
                $category->save();
                Scenario::createEmptyScenario($category->id);
                Yii::$app->session->setFlash('success', 'Новая категория успешно создана.');
                return $this->redirect(['index']);
            }
            else
            {
                Yii::$app->session->setFlash('error', 'Категория с таким наименованием уже создана.');
                return $this->redirect(['index']);
            }
        }
    }

    public function actionUpdate()
    {
        $request = Yii::$app->request;
        if(Yii::$app->request->isGet)
        {
            $id = (int)$request->get('id');
            $category = BusinessEnvironment::find()->where(['id' => $id])->one();
            return $this->render('updateForm', ['category' => $category]);
        }
        if(Yii::$app->request->isPost)
        {
            $id = (int)$request->get('id');
            $category = BusinessEnvironment::find()->where(['id' => $id])->one();
            $categoryName = $request->post('CategoryName');
            $categoryStatus = $request->post('Main');
            $category->name = $categoryName;
            $category->main = $categoryStatus;
            $category->save();
            Yii::$app->session->setFlash('success', 'Изменения успешно сохранены.');
            return $this->actionindex();
        }

    }

    public function actionDelete()
    {
        $request = Yii::$app->request;
        if(Yii::$app->request->isGet)
        {
            $id = (int)$request->get('id');
            $category = BusinessEnvironment::findOne($id);
            return $this->render('deleteForm', ['category' => $category]);
        }
        if(Yii::$app->request->isPost)
        {
            $id = (int)$request->get('id');
            $category = BusinessEnvironment::find()->where(['id' => $id])->one();
            Scenario::deleteScenario($category->id);
            $category->delete();
            Yii::$app->session->setFlash('success', 'Категория успешно удалена.');
            return $this->actionindex();
        }
    }
}

SII/backend/views/environment/createForm.php
<?php
use yii\helpers\Html;

$this->title = 'Создать новую категорию';
?>
<div class="container-fluid">
    <h1>Создать новую категорию</h1>

    <?php

    $mainForm = Html::beginForm(['environment/create'], 'post');
    $mainForm .= "<br>";
    $mainForm .= "<div class='form-group'>";
    $mainForm .= Html::label('Название категории:', ['class' => 'control-label']);
    $mainForm .= Html::input('text', 'CategoryName', '', ['class' => 'form-control']);
    $mainForm .= "</div class='form-group'>";
    $mainForm .= "<div class='form-group'>";
    $mainForm .= Html::label('Статус категории:', ['class' => 'control-label']);
    $mainForm .= Html::dropDownList('Main', 0, [1 => 'Основная', 0 => 'Дополнительная'], ['class' => 'form-control']);
    $mainForm .= "</div class='form-group'>";
    $mainForm .= Html::submitButton('<i class="glyphicon glyphicon-plus"></i> Создать', ['class' => 'btn btn-success', 'name' => 'contact-button']);
    $mainForm .= Html::endForm();
    echo $mainForm;
    ?>
</div>

SII/backend/views/environment/deleteForm.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
$this->title = 'Удалить категорию';
?>
<div class="container-fluid">
    <h1><?= $category->name ?></h1>
    <p class="text-danger">Вы действительно хотите удалить данную категорию делового окружения?</p>
    <div class="row-fluid">

        <?php
        $form = Html::beginForm(['environment/delete', 'id' => $category->id], 'post');
        $form .= Html::submitButton('<span class="glyphicon glyphicon-trash"></span> Удалить', ['class' => 'btn btn-danger']);
        $form .= Html::endForm();
        echo $form;
        ?>
        <br>
        <?php
        $form = Html::beginForm(['environment/index'], 'get');
        $form .= Html::submitButton('<i class="fa fa-reply"></i> Отмена', ['class' => 'btn btn-success']);
        $form .= Html::endForm();
        echo $form;
        ?>


    </div>

</div>

SII/backend/views/environment/index.php
<?php
use yii\helpers\Html;
use yii\grid\GridView;
use yii\data\ActiveDataProvider;
use common\models\BusinessEnvironment;
$this->title = 'Категории делового окружения';
$сategoriesHtml = Html::a('<i class="glyphicon glyphicon-plus"></i> Добавить категорию', ['environment/create'], ['class' => 'btn btn-success']);
$сategoriesHtml .= "<br><br>";
$dataProvider = new ActiveDataProvider([
    'query' => BusinessEnvironment::find(),
]);
$сategoriesHtml .= GridView::widget([
    'dataProvider' => $dataProvider,
    'columns' => [
        'name',
        [
            'class' => 'yii\grid\DataColumn',
            'attribute' => 'main',
            'content' => function($model, $key, $index, $column){
                if ($model->main == 1)
                {
                    return '<span class="label label-success">Основная</span>';
                }
                else
                {
                    return '<span class="label label-primary">Дополнительная</span>';
                }
            }
        ],
        [
            'class' => 'yii\grid\ActionColumn',
            'template' => '{update} {delete}',
            'buttons' => [
                'delete' => function ($url, $model, $key) {
                    return Html::a("<span class='glyphicon glyphicon-trash'></span>", $url, ['title' => 'Удалить']);
                }
            ]
        ],
    ],
    'tableOptions' => ['class' => 'table table-bordered table-hover dataTable'],
    'summary' => ''
]);
?>
<div class="container-fluid">
    <h1>Категории делового окружения</h1>
    <?= $сategoriesHtml ?>
</div>

SII/backend/views/environment/updateForm.php
<?php
use yii\helpers\Html;
$this->title = 'Изменить категорию делового окружения';
?>
<div class="container-fluid">
    <h1><?= $category->name ?></h1>
    <?php
    $form = Html::beginForm(['environment/update', 'id' => $category->id], 'post');
    $form .= "<br>";
    $form .= "<div class='form-group'>";
    $form .= Html::label('Название категории:', ['class' => 'control-label']);
    $form .= Html::input('text', 'CategoryName', $category->name, ['class' => 'form-control']);
    $form .= "</div class='form-group'>";
    $form .= "<div class='form-group'>";
    $form .= Html::label('Статус категории:', ['class' => 'control-label']);
    $form .= Html::dropDownList('Main', $category->main, [1 => 'Основная', 0 => 'Дополнительная'], ['class' => 'form-control']);
    $form .= "</div class='form-group'>";
    $form .= Html::submitButton('<i class="fa fa-floppy-o"></i> Сохранить изменения', ['class' => 'btn btn-success']);
    $form .= Html::endForm();
    echo $form;
    ?>
</div>